### ISSUE TITLE
Media ID must be Spotify uri?

### ISSUE THREAD

**Issue by fmonday** [rotx/homeassistant-components#2]
This looks very promising, but after properly installing and restarting, I tried to call `tts.macos_tts_say` as per your component test, and it fails with the below error. Very unexpected. 

```
tts:
  - platform: macos_tts
    voice: 'Samantha'

media_player:
  - platform: macos_tts
```

```
2019-10-29 19:52:02 ERROR (SyncWorker_12) [homeassistant.components.spotify.media_player] media id must be spotify uri
Error: AudioFileOpen failed ('dta?')
```

OS: 10.15 (mac mini)
HA: 0.100.3

**Comment by rotx** [comment]
Sorry, I don't have Spotify. It does sound like the selected media player is Spotify, and that Spotify doesn't want to play anything that it doesn't know about (such as local files?).
The last version these plugins were tested on was HA 0.96 under macOS 10.13.6.

**Comment by fmonday** [comment]
I have four media players defined, one of which is indeed Spotify. Is there something to do to specify that the `tts.macos_tts_say` service uses the `macos_tts` media player platform?

**Comment by rotx** [comment]
It looks like this can be done by specifying the `entity_id` when defining the `service`. The Home Assistant docs show the following example for Polly TTS. This method might work for the macOS TTS as well (not tested). Let me know what you find out.

```
- service: tts.amazon_polly_say
  data_template:
    entity_id: media_player.living_room
    message: '<speak>Hello from Amazon Polly</speak>'
```
